name: "Shellcheck Lint"
on: push
jobs:
  shellcheck:
    name: "Shellcheck Lint"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: "Run shellcheck.sh"
        run: |
          ./development/shellcheck.sh
