name: CI
on: [push]
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
      - uses: actions/checkout@v2
      - name: install
        run: |
          apt install shellcheck jq -y;
      - name: run
        run: |
          ./development/shellcheck.sh
